# Copyright 2013 by Martin Moene
#
# Distributed under the Boost Software License, Version 1.0. (See accompanying
# file LICENSE_1_0.txt or copy at http://www.boost.org/LICENSE_1_0.txt)

CXXFLAGS   := -Wall -Wextra -Weffc++ -Wno-missing-braces -I..
CXXFLAGS03 := $(CXXFLAGS) -std=c++03
CXXFLAGS11 := $(CXXFLAGS) -std=c++11

vpath %.hpp ..

all: test_lest.exe test_lest_decompose.exe test_lest_cpp03.exe

test_lest.exe: test_lest.cpp lest.hpp
	$(CXX) $(CXXFLAGS11) -o test_lest test_lest.cpp
	test_lest

test_lest_decompose.exe: test_lest_decompose.cpp lest_decompose.hpp
	$(CXX) $(CXXFLAGS11) -o test_lest_decompose test_lest_decompose.cpp
	test_lest_decompose

test_lest_cpp03.exe: test_lest_cpp03.cpp lest_cpp03.hpp
	$(CXX) $(CXXFLAGS03) -o test_lest_cpp03 test_lest_cpp03.cpp
	test_lest_cpp03

clean:
	rm test_lest.exe test_lest_decompose.exe test_lest_cpp03.exe

